apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-version
spec:
  steps:
    - name: echo
      image: quay.io/argoproj/argocd
      script: |
        #!/bin/sh
        argocd login http://localhost:8080 \
          --username admin \
          --password KHaoBjUSt9TmLJ2K \
          --insecure

        argocd version