apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-version
spec:
  steps:
    - name: echo
      image: quay.io/argoproj/argocd
      script: |
        #!/bin/sh
        argocd login $(kubectl get service argocd-server -n argocd --output=jsonpath='{.status.loadBalancer.ingress[0].hostname}') \
          --username admin \
          --password $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo) \
          --insecure

        argocd version